export const endpoints = [
  // ===== Upload APIs =====
  {
    id: 'update-phr-v1',
    name: 'UpdatePHRv1',
    group: 'upload',
    method: 'POST',
    path: '/api/UpdatePHRv1',
    description: 'Upload ข้อมูลสุขภาพแบบเต็ม',
    authRequired: true,
  },
  {
    id: 'allergy-v1',
    name: 'AllergyIntolerancev1',
    group: 'upload',
    method: 'POST',
    path: '/api/AllergyIntolerancev1',
    description: 'ส่งข้อมูลการแพ้ยา',
    authRequired: true,
  },
  {
    id: 'chronic-register-v1',
    name: 'PatientChronicRegisterv1',
    group: 'upload',
    method: 'POST',
    path: '/api/PatientChronicRegisterv1',
    description: 'ขึ้นทะเบียนโรคเรื้อรัง',
    authRequired: true,
  },
  {
    id: 'immunization-v1',
    name: 'ImmunizationRegisterv1',
    group: 'upload',
    method: 'POST',
    path: '/api/ImmunizationRegisterv1',
    description: 'ส่งข้อมูลวัคซีน',
    authRequired: true,
  },
  {
    id: 'referral-request',
    name: 'ReferralRequest',
    group: 'upload',
    method: 'POST',
    path: '/api/ReferralRequest',
    description: 'ส่งข้อมูลการส่งต่อ',
    authRequired: true,
  },
  {
    id: 'self-observation',
    name: 'SelfObservation',
    group: 'upload',
    method: 'POST',
    path: '/api/SelfObservation',
    description: 'ส่งข้อมูล Vital Sign จาก Home Monitoring',
    authRequired: true,
  },
  {
    id: 'caregiver',
    name: 'CareGiver',
    group: 'upload',
    method: 'POST',
    path: '/api/CareGiver',
    description: 'ส่งข้อมูลผู้ดูแลผู้ป่วย',
    authRequired: true,
  },
  {
    id: 'encounter-summary',
    name: 'OrgEncounterSummary',
    group: 'upload',
    method: 'POST',
    path: '/api/OrgEncounterSummary',
    description: 'สรุปจำนวน Encounter',
    authRequired: true,
  },

  // ===== Retrieval APIs =====
  {
    id: 'patient-summary',
    name: 'PatientSummary',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=PatientSummary',
    description: 'ข้อมูลภาพรวมผู้ป่วย',
    authRequired: true,
  },
  {
    id: 'encounter',
    name: 'Encounter',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Encounter',
    description: 'ประวัติการเข้ารับบริการ',
    authRequired: true,
  },
  {
    id: 'vital-sign',
    name: 'VitalSign',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=VitalSign',
    description: 'ข้อมูล Vital Sign',
    authRequired: true,
  },
  {
    id: 'condition',
    name: 'Condition',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Condition',
    description: 'ผลวินิจฉัย',
    authRequired: true,
  },
  {
    id: 'condition-encounter',
    name: 'Condition (by Encounter)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Condition&mode=Encounter&Code=xxxx',
    description: 'ผลวินิจฉัยแยกตาม Encounter',
    authRequired: true,
  },
  {
    id: 'observation',
    name: 'Observation',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Observation',
    description: 'ผลตรวจทางห้องปฏิบัติการ',
    authRequired: true,
  },
  {
    id: 'observation-detail',
    name: 'Observation (Detail)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Observation&mode=Detail',
    description: 'ผลตรวจแยกตามรายการ',
    authRequired: true,
  },
  {
    id: 'observation-encounter',
    name: 'Observation (by Encounter)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Observation&mode=Encounter&Code=xxxx',
    description: 'ผลตรวจแยกตาม Encounter',
    authRequired: true,
  },
  {
    id: 'medication',
    name: 'Medication',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Medication',
    description: 'รายการยาที่ได้รับ',
    authRequired: true,
  },
  {
    id: 'medication-encounter',
    name: 'Medication (by Encounter)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Medication&mode=Encounter&Code=xxxx',
    description: 'รายการยาแยกตาม Encounter',
    authRequired: true,
  },
  {
    id: 'coverage',
    name: 'Coverage',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Coverage',
    description: 'สิทธิการรักษา',
    authRequired: true,
  },
  {
    id: 'coverage-detail',
    name: 'Coverage (Detail)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Coverage&mode=Detail',
    description: 'สิทธิการรักษาแยกตาม Encounter',
    authRequired: true,
  },
  {
    id: 'appointment',
    name: 'Appointment',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Appointment',
    description: 'ข้อมูลนัดหมาย',
    authRequired: true,
  },
  {
    id: 'immunization-detail',
    name: 'Immunization (Detail)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Immunization&mode=Detail',
    description: 'ข้อมูลวัคซีนที่ได้รับ',
    authRequired: true,
  },
  {
    id: 'allergy',
    name: 'Allergy',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Allergy',
    description: 'ข้อมูลการแพ้ยา',
    authRequired: true,
  },
  {
    id: 'ncd',
    name: 'NCD',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=NCD',
    description: 'ข้อมูลโรคเรื้อรัง',
    authRequired: true,
  },
  {
    id: 'referral',
    name: 'Referral',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Referral',
    description: 'ข้อมูลการส่งต่อ',
    authRequired: true,
  },
  {
    id: 'self-observation-read',
    name: 'SelfObservation (Read)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=SelfObservation',
    description: 'ข้อมูล Self Observation',
    authRequired: true,
  },
  {
    id: 'caregiver-read',
    name: 'CareGiver (Read)',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=CareGiver&mode=2',
    description: 'ข้อมูลผู้ดูแล',
    authRequired: true,
  },
  {
    id: 'pregnancy',
    name: 'Pregnancy',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=Pregnancy',
    description: 'ข้อมูลการตั้งครรภ์',
    authRequired: true,
  },
  {
    id: 'profile-image',
    name: 'ProfileImage',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=ProfileImage',
    description: 'รูป Profile',
    authRequired: true,
  },
  {
    id: 'diagnostic-report',
    name: 'DiagnosticReport',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=DiagnosticReport&mode=Encounter&Code=xxxx',
    description: 'ผลอ่านฟิลม์รังสี',
    authRequired: true,
  },
  {
    id: 'report-encounter',
    name: 'ReportEncounter',
    group: 'retrieval',
    method: 'POST',
    path: '/api/WebApp?Action=ReportEncounter',
    description: 'รายการแจ้งข้อมูลไม่ถูกต้อง',
    authRequired: true,
  },

  // ===== Utility APIs =====
  {
    id: 'update-agent-status',
    name: 'UpdateAgentStatus',
    group: 'utility',
    method: 'POST',
    path: '/api/UpdateAgentStatus',
    description: 'อัพเดทสถานะ Agent',
    authRequired: true,
  },
  {
    id: 'update-agent-status-error',
    name: 'UpdateAgentStatus (Error)',
    group: 'utility',
    method: 'POST',
    path: '/api/UpdateAgentStatus?mode=Error',
    description: 'แจ้ง Error สถานะ Agent',
    authRequired: true,
  },
  {
    id: 'get-agent-computer',
    name: 'GetAgentComputerName',
    group: 'utility',
    method: 'POST',
    path: '/api/GetAgentComputerName',
    description: 'ตรวจสอบชื่อ Agent',
    authRequired: true,
  },
  {
    id: 'org-summary-daily',
    name: 'OrganizationSummary (Daily)',
    group: 'utility',
    method: 'GET',
    path: '/api/OrganizationSummary',
    description: 'ตรวจสอบ Encounter รายวัน',
    authRequired: true,
    queryParams: ['date', 'data', 'hospital_code'],
  },
  {
    id: 'org-summary-monthly',
    name: 'OrganizationSummary (Monthly)',
    group: 'utility',
    method: 'GET',
    path: '/api/OrganizationSummary',
    description: 'สรุปข้อมูลรายเดือน',
    authRequired: true,
    queryParams: ['month', 'data', 'hospital_code'],
  },
  {
    id: 'remove-encounter',
    name: 'RemoveEncounter',
    group: 'utility',
    method: 'GET',
    path: '/api/RemoveEncounter',
    description: 'ลบข้อมูล Encounter',
    authRequired: true,
    queryParams: ['hospital_code', 'encounter_ref_code'],
  },
  {
    id: 'paste-json-post',
    name: 'PasteJSON (POST)',
    group: 'utility',
    method: 'POST',
    path: '/api/PasteJSON?Action=POST',
    description: 'ฝากข้อมูล Payload ชั่วคราว',
    authRequired: true,
  },
  {
    id: 'paste-json-get',
    name: 'PasteJSON (GET)',
    group: 'utility',
    method: 'GET',
    path: '/api/PasteJSON?Action=GET',
    description: 'ดึงข้อมูล Payload',
    authRequired: true,
    queryParams: ['code'],
  },
  {
    id: 'mask-encounter-set',
    name: 'MaskEncounter (Set)',
    group: 'utility',
    method: 'POST',
    path: '/api/MaskEncounter?mode=set',
    description: 'ซ่อนข้อมูล Encounter',
    authRequired: true,
  },
  {
    id: 'mask-encounter-get',
    name: 'MaskEncounter (Get)',
    group: 'utility',
    method: 'POST',
    path: '/api/MaskEncounter?mode=get',
    description: 'ตรวจสอบข้อมูลที่ซ่อน',
    authRequired: true,
  },
  {
    id: 'phr-setting-set',
    name: 'PHRSetting (Set)',
    group: 'utility',
    method: 'POST',
    path: '/api/PHRSetting?mode=set',
    description: 'กำหนดค่า Sharing Preferences',
    authRequired: true,
  },
  {
    id: 'phr-setting-get',
    name: 'PHRSetting (Get)',
    group: 'utility',
    method: 'POST',
    path: '/api/PHRSetting?mode=get',
    description: 'ตรวจสอบ Sharing Preferences',
    authRequired: true,
  },
  {
    id: 'request-token-v1',
    name: 'RequestTokenv1',
    group: 'utility',
    method: 'POST',
    path: '/api/RequestTokenv1',
    description: 'ขอ OTP',
    authRequired: true,
  },
  {
    id: 'validate-otp',
    name: 'ValidateOTP',
    group: 'utility',
    method: 'POST',
    path: '/api/WebApp?Action=ValidateOTP',
    description: 'ตรวจสอบ OTP',
    authRequired: true,
  },
  {
    id: 'get-phr-otp',
    name: 'GetPHROTP',
    group: 'utility',
    method: 'POST',
    path: '/api/GetPHROTP',
    description: 'ขอ OTP จาก SmartCard',
    authRequired: true,
  },
  {
    id: 'check-ekyc',
    name: 'Check eKYC',
    group: 'utility',
    method: 'POST',
    path: '/idp/api/check_ekyc',
    description: 'ตรวจสอบสถานะ eKYC',
    authRequired: true,
  },
  {
    id: 'report-encounter-add',
    name: 'ReportEncounter (Add)',
    group: 'utility',
    method: 'POST',
    path: '/api/WebApp?Action=ReportEncounter&mode=ADD',
    description: 'แจ้งข้อมูลไม่ถูกต้อง',
    authRequired: true,
  },
  {
    id: 'report-encounter-delete',
    name: 'ReportEncounter (Delete)',
    group: 'utility',
    method: 'POST',
    path: '/api/WebApp?Action=ReportEncounter&mode=DELETE',
    description: 'ลบรายงานข้อมูลไม่ถูกต้อง',
    authRequired: true,
  },
  {
    id: 'report-encounter-list',
    name: 'ReportEncounter (List)',
    group: 'utility',
    method: 'POST',
    path: '/api/WebApp?Action=ReportEncounter&mode=LIST',
    description: 'รายการแจ้งข้อมูลไม่ถูกต้อง',
    authRequired: true,
  },
]

export function getEndpointsByGroup(group) {
  return endpoints.filter(e => e.group === group)
}

export function getEndpointById(id) {
  return endpoints.find(e => e.id === id)
}

export function getGroupLabel(group) {
  const labels = { upload: 'Upload APIs', retrieval: 'Retrieval APIs', utility: 'Utility APIs' }
  return labels[group] || group
}
